### ISSUE TITLE
Lack of method for checking biometric enrollment (issue reported)

### ISSUE THREAD

**Issue by ronakmob** [Kieun/android-biometricprompt#5]
Hi,

Thank you for providing the wonderful ease code. 

Of course I am not able to detect User has enrolled for biometric or not. I found following document which emphasize that this is Intended behaviour. We can catch this error using `BIOMETRIC_ERROR_NO_BIOMETRICS` but unfortunately it didn't work out with the sample code.

I am trying to catch error in `getAuthenticationCallback` => `onAuthenticationError`  

Stackoverflow: https://stackoverflow.com/questions/50968732/determine-if-biometric-hardware-is-present-and-the-user-has-enrolled-biometrics

Google Tracker: https://issuetracker.google.com/issues/109826221

Removing `signature` param from `authenticate` works fine but I would like to have crypto signature.

Am I doing anything wrong. I would be thankful for your help.

**Comment by Kieun** [comment]
Before Android Q, you need to check fingerprint manager. But for Android Q+, you can check BiometricManager components.
